-- FOREIGN KEY IMPLEMENTATION-- 

CREATE DATABASE UNIVERSITY;
USE UNIVERSITY;

CREATE TABLE DEPARTMENT(
ID INT PRIMARY KEY,
SUBJECT VARCHAR(50));

CREATE TABLE TEACHER_INFORMATION(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
DEPT_ID INT,
FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(ID)
ON UPDATE CASCADE
ON DELETE CASCADE);

INSERT INTO DEPARTMENT
(ID, SUBJECT)
VALUES
(01, "SCIENCE"),
(02, "ENGLISH"),
(03,"CULT EDUCATION");

INSERT INTO TEACHER_INFORMATION
(ID, NAME, DEPT_ID)
VALUES
(101, "BILTU DAA",01),
(102, "RAJU DAA",02),
(103,"KELO KAKA",02),
(104, "PRASANTA BHAI", 03),
(105,"ENGLES FEDRICK", 04);

INSERT INTO DEPARTMENT
(ID,SUBJECT)
VALUES
(04,"ENGINEERING"),
(05,"STATICTIS");

INSERT INTO TEACHER_INFORMATION
(ID, NAME, DEPT_ID)
VALUES
(105,"ENGLES FEDRICK", 04),
(05,"STAT MOSHAI", 05);

UPDATE DEPARTMENT
SET ID = 9
WHERE ID = 04;

SELECT * FROM DEPARTMENT;

-- TABLE RELATED QUEIRIES -- 
-- 1. ADD COLUMN-- 
ALTER TABLE TEACHER_INFORMATION
ADD COLUMN AGE INT NOT NULL DEFAULT 512;

-- 2.MODIFY-- 
ALTER TABLE TEACHER_INFORMATION
MODIFY COLUMN AGE VARCHAR(2);

-- 3.CHANGE -- 
ALTER TABLE TEACHER_INFORMATION
CHANGE AGE FACULTY_AGE INT;

-- 4.DROP COLUMN-- 
ALTER TABLE TEACHER_INFORMATION
DROP COLUMN FACULTY_AGE;

-- 5.RENAME TABLE--
ALTER TABLE TEACHER_INFORMATION
RENAME TO T_INFO; 

-- 6.TRUNCATE(DELETES ALL TABLE DATA)--
TRUNCATE TABLE T_INFO;

SELECT * FROM T_INFO;