CREATE DATABASE COLLEGE;
USE COLLEGE;

CREATE TABLE STUDENT(
ROLL_NO INT PRIMARY KEY,
NAME VARCHAR(100),
MARKS INT NOT NULL,
GRADE VARCHAR(1),
CITY VARCHAR(50)
);

INSERT INTO STUDENT
 (ROLL_NO, NAME, MARKS, GRADE, CITY) 
 VALUES
 (1, "KHOKABABU JUTO CHOR", 78, "B", "KOLKATA"),
 (2, "NEEL ARMSTRONG", 12, "D", "MINNESOTA"),
 (3,"YOGI ADITYANATH", 99, "A", "CRIMINAL PUR");
 
 SELECT * FROM STUDENT;
 SELECT * FROM STUDENT LIMIT 2;
 SELECT * FROM STUDENT WHERE MARKS NOT IN (70,99);
 SELECT * FROM STUDENT ORDER BY MARKS ASC;
 SELECT COUNT(NAME) FROM STUDENT;
 SELECT CITY, NAME, COUNT(MARKS) FROM STUDENT GROUP BY CITY, NAME;
 
 INSERT INTO STUDENT
 (ROLL_NO, NAME, MARKS, GRADE, CITY) 
 VALUES
 (4, "CHONDROCCHUR GHOSH", 88, "B", "KOLKATA");