CREATE DATABASE COLLEGE2;
USE COLLEGE2;

CREATE TABLE STUDENT(
ROLL_NO INT PRIMARY KEY,
NAME VARCHAR(100),
MARKS INT NOT NULL,
GRADE VARCHAR(1),
CITY VARCHAR(50)
);

INSERT INTO STUDENT
 (ROLL_NO, NAME, MARKS, GRADE, CITY) 
 VALUES
 (1, "KHOKABABU JUTO CHOR", 78, "B", "KOLKATA"),
 (2, "NEEL ARMSTRONG", 12, "D", "MINNESOTA"),
 (3,"YOGI ADITYANATH", 99, "A", "CRIMINAL PUR"),
 (4, "CHONDROCCHUR GHOSH", 88, "B", "KOLKATA");
 
 SELECT CITY,AVG(MARKS) FROM STUDENT GROUP BY CITY ORDER BY AVG(MARKS) ASC;